[package]
name = "pet-blackhole"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
ash = "0.38"
ash-window = "0.13"
env_logger = "0.11"
glam = "0.30"
log = "0.4"
raw-window-handle = "0.6"
winit = "0.30"

[target.'cfg(windows)'.dependencies]
windows = { version = "0.62", features = [
  "Win32_Foundation",
  "Win32_Graphics_Gdi",
] }

[target.'cfg(windows)'.build-dependencies]
winresource = "0.1"

